# -*- coding: utf-8 -*-
"""quick_sort.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zh4cPC-gjxq8SEFzJbp79nEtTkXOTtj2
"""

import random

def quick_sort(array, start, end):
    p = start
    r = end
    q = p
    for i in range(p, r):
      if array[i] <= array[r] :
        temp = array[q]
        array[q] = array[i]
        array[i] = temp
        q += 1

    if p < r:
      temp = array[q]
      array[q] = array[r]
      array[r] = temp
      
      quick_sort(array, p, q-1)
      quick_sort(array, q+1, r)
       

"""rand_int_array = []
for i in range(10000):
  rand_int_array.append(random.randint(0,100))"""

array = [60,12,9,44,1,20,35,70,88,18]

quick_sort(array, 0 , len(array)-1)
print(array)